version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=java -jar agent.jar -url http://localhost:8080/ -secret 952141bb70bf2db47bf560ffc8be7d71b6b78d643bc2a21163bb1b7214033706 -name "docker-agent" -workDir "/home/jenkins/agent"
      - JENKINS_AGENT_NAME=docker-agent
    depends_on:
      - jenkins

volumes:
  jenkins_home:
